(source gnu)
(source melpa)

(depends-on "auctex")
(depends-on "better-defaults")
(depends-on "ein")
(depends-on "elpy")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "py-isort")
(depends-on "yapfify")
(depends-on "yasnippet")
(depends-on "yasnippet-snippets")
(depends-on "zenburn-theme")
