channels:
  - conda-forge
  - bioconda
dependencies:
  - autoconf
  - automake
  - black
  - cmake
  - compilers
  - emacs=28
  - git
  - isort
  - jupyter
  - libtool
  - pandoc>=2.19.2
  - pkg-config
  - pre-commit
  - pyright
  - python=3.10
  - snakefmt
