channels:
  - conda-forge
  - bioconda
dependencies:
  - autoconf
  - automake
  - black
  - ca-certificates
  - clangdev
  - cmake
  - compilers
  - emacs=28
  - epc
  - flake8
  - git
  - glib
  - isort
  - jedi
  - jupyter
  - libtool
  - lxml
  - make
  - nodejs
  - openssl
  - pandoc
  - pip
  - pkg-config
  - pre-commit
  - pygit2
  - pyqt
  - pyqtwebengine
  - pyright
  - snakefmt
  - tectonic=0.8
  - terraform
  - wmctrl
  - pip:
      - importmagic
name: emacs
