name: emacs
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pip:
    - importmagic
    - pymupdf
  - black    
  - clangdev
  - cmake
  - compilers
  - emacs=27.2
  - epc
  - flake8
  - glib
  - isort  
  - jedi
  - jupyter
  - libtool
  - lxml
  - make
  - nodejs
  - pandoc
  - pyqt
  - pyqtwebengine
  - pygit2  
  - snakefmt
  - tectonic=0.8
  - wmctrl
