channels:
  - conda-forge
  - bioconda
dependencies:
  - autoconf
  - automake
  - cmake
  - compilers
  # - emacs=28
  - git
  - jupyter
  - libtool
  - pandoc>=2.19.2
  - pkg-config
  - pre-commit
  - pyright
  - python=3.10
  - ruff>=0.4.0
  - snakefmt
