name: emacs
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pip:
    - importmagic
  - black    
  - clangdev
  - cmake
  - compilers
  - emacs=27
  - flake8
  - isort  
  - jedi
  - jupyter
  - libtool
  - make
  - pandoc
  - snakefmt
