name: emacs
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - importmagic
  - autoconf
  - automake
  - black    
  - clangdev
  - cmake
  - emacs=27
  - flake8
  - isort  
  - jedi
  - jupyter
  - libtool
  - pandoc
  - pkg-config
  - zeromq
