name: emacs
channels:
  - conda-forge
  - bioconda
dependencies:
  - autoconf
  - automake
  - black
  - clangdev
  - cmake
  - compilers
  - emacs=28
  - epc
  - flake8
  - glib
  - isort
  - jedi
  - jupyter
  - libtool
  - lxml
  - make
  - nodejs
  - pandoc
  - pip
  - pip:
    - importmagic
  - pkg-config
  - pyqt
  - pyqtwebengine
  - pygit2
  - pyright
  - snakefmt
  - tectonic=0.8
  - terraform
  - wmctrl
